---
- hosts: packages
  serial: 1
  gather_facts: no
  tasks:
    - fail:
        msg: "'upstream_files' not defined for {{ inventory_hostname }}. Please define within package_manifest.yml"
      when: upstream_files is not defined

    - name: 'Make package directory'
      file:
        state: 'directory'
        path: "packages/{{ inventory_hostname }}"
      register: package_directory_result


    - block:
        - include: download_and_extract_source.yml

        - name: 'Git annex add new package'
          command: "git annex add packages/{{ inventory_hostname }}/{{ item }}"
          with_items: "{{ annex }}"
          when: annex is defined

        - name: 'Git add new package'
          command: "git add packages/{{ inventory_hostname }}/*"

        - name: 'Check if changes in package'
          command: 'git status -s packages/{{ inventory_hostname }}'
          register: git_status

        - name: 'Git commit new package'
          command: "git commit packages/{{ inventory_hostname }} -m 'Add {{ inventory_hostname }}'"
          when: git_status.stdout != ''

        - name: 'Git add new package'
          command: "git add packages/{{ inventory_hostname }}/*"
          when: git_status.stdout != ''
      when: package_directory_result|changed
