---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: install required packages
      yum:
        name: "{{ item }}"
        state: latest
      become: true
      with_items:
        - rpm-build
        - koji
        - brewkoji
        - git-annex
        - quvi
        - tito
        - rhpkg
        - scl-utils
        - scl-utils-build

- hosts: packages
  serial: 1
  gather_facts: no
  roles:
    - git-annex-setup
    - ensure-package
    - diff-brew-package
  tasks:
    - meta: end_play
      when: not rhel5_build_needed and not rhel6_build_needed and not rhel7_build_needed
      tags:
        - always

    - debug:
        msg: "Version compare for EL5: brew:[ {{ latest_brewed_rhel5 }} ] local:[ {{ latest_local_rhel5 }} ]"
      when: rhel5_branch_exists | bool
      tags:
        - always

    - debug:
        msg: "Version compare for EL6: brew:[ {{ latest_brewed_rhel6 }} ] local:[ {{ latest_local_rhel6 }} ]"
      when: rhel6_branch_exists | bool
      tags:
        - always

    - debug:
        msg: "Version compare for EL7: brew:[ {{ latest_brewed_rhel7 }} ] local:[ {{ latest_local_rhel7 }} ]"
      when: rhel7_branch_exists | bool
      tags:
        - always

    - name: 'Run setup_sources'
      shell: "./setup_sources.sh {{ inventory_hostname }}"
      args:
        chdir: "packages"
      tags:
        - always

    - name: 'Release to brew'
      shell: "tito release {{ joined_releasers }} -y"
      args:
        chdir: "packages/{{ inventory_hostname }}"
      register: brew_release
      tags:
        - always

    - debug:
        msg: "{{ brew_release.stdout_lines }}"
      when: brew_release | succeeded
      tags:
        - always

    - debug:
        msg: "{{ brew_release.stderr.split('\n') }}"
      when: brew_release | failed
      tags:
        - always

    # we use this to ensure that `wait` tagged tasks only run with `--tags
    # wait` is passed
    - command: /bin/true
      register: normal_execution_check

    - set_fact:
        brew_tasks: "{{ brew_release.stdout_lines \
          | select('match', '^Created task:.*') \
          | map('regex_replace', '^Created task:\\s(\\d+)', '\\1') \
          | list }}"
      when: normal_execution_check is not defined
      tags:
        - wait

    - name: 'Watch brew task(s)'
      command: "brew watch-task {{ brew_tasks | join(' ') }}"
      when: (brew_release | succeeded) and (normal_execution_check is not defined)
      tags:
        - wait

