---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: install required packages
      yum:
        name: "{{ item }}"
        state: latest
      become: true
      with_items:
        - rpm-build
        - koji
        - brewkoji
        - git-annex
        - quvi
        - tito
        - rhpkg
        - scl-utils
        - scl-utils-build

- hosts: packages
  serial: 1
  gather_facts: no
  roles:
    - git-annex-setup
    - ensure-package
    - diff-brew-package
  tasks:
    - meta: end_play
      when: not rhel5_build_needed and not rhel6_build_needed and not rhel7_build_needed
      tags:
        - always

    - debug:
        msg: "Version compare for EL5: brew:[ {{ latest_brewed_rhel5 }} ] local:[ {{ latest_local_rhel5 }} ]"
      changed_when: rhel5_branch_exists | bool
      when: rhel5_branch_exists | bool
      tags:
        - always

    - debug:
        msg: "Version compare for EL6: brew:[ {{ latest_brewed_rhel6 }} ] local:[ {{ latest_local_rhel6 }} ]"
      changed_when: rhel6_branch_exists | bool
      when: rhel6_branch_exists | bool
      tags:
        - always

    - debug:
        msg: "Version compare for EL7: brew:[ {{ latest_brewed_rhel7 }} ] local:[ {{ latest_local_rhel7 }} ]"
      changed_when: rhel7_branch_exists | bool
      when: rhel7_branch_exists | bool
      tags:
        - always

    - include: tasks/setup_sources.yml

    - set_fact:
        tito_releasers: "{{ joined_releasers }}"
      tags:
        - always

    - include: tasks/tito_release.yml

    - include: tasks/brew_wait_and_download.yml
