---
- hosts: packages
  serial: 1
  gather_facts: no
  tasks:
    - fail:
        msg: "'upstream_files' not defined for {{ inventory_hostname }}. Please define within package_manifest.yml"
      when:
        - upstream_files is not defined
        - downstream_version is not defined

    - name: Determine source file from spec
      shell: "spectool --list-files --source 0 *.spec"
      args:
        chdir: "packages/{{ inventory_hostname }}"
      register: source_url

    - set_fact:
        source: "{{ source_url.stdout.split('\n')[0].split('/')[-1] }}"

    - name: "Remove old source"
      command: "git rm --ignore-unmatch {{ source }}"
      args:
        chdir: "packages/{{ inventory_hostname }}"

    - include: tasks/download_and_extract_source.yml

    - name: Determine new source file from spec
      shell: "spectool --list-files --source 0 *.spec"
      args:
        chdir: "packages/{{ inventory_hostname }}"
      register: source_url

    - set_fact:
        source: "{{ source_url.stdout.split('/')[-1] }}"

    - name: 'Git annex add new package'
      command: "git annex add packages/{{ inventory_hostname }}/{{ source }}"
